### ISSUE TITLE
[デザイン班]デザインを描く

### ISSUE THREAD

**Issue by Issei0804-ie** [Issei0804-ie/himeji#2]
後ほど振り返りをしやすいように，ここにデザインを貼って done してくれると :pray:

**Comment by Issei0804-ie** [comment]
![external-content duckduckgo](https://user-images.githubusercontent.com/52270000/101711533-12a33e80-3ad7-11eb-821a-1643dd7cf92a.jpg)

**Comment by ShoAsato** [comment]
![IMG_2013](https://user-images.githubusercontent.com/57646396/101711713-7a598980-3ad7-11eb-867e-0c2d64987078.jpeg)
